### ISSUE TITLE
Version '1.8.17+build15807+xenial' for 'ethereum' was not found

### ISSUE THREAD

**Issue by kyriediculous** [javahippie/geth-dev#45] opened 2018-11-15 12:48 UTC
Since the geth version is still being hardcoded as environment variable and the PPA repository changes tags after a new release (or doesnt have old release even ,I have not checked) we are getting an error on launching or docker containers. 

The current version is 1.8.18 , I suggest omtting the `$binary` environment variable completely and just rolling with the latest versions of geth and swarm.

`E: Version '1.8.17+build15807+xenial' for 'ethereum' was not found`

I will submit a PR.

**Comment by javahippie** [comment] 2018-11-15 12:59
Setting the versions to "latest" is not ideal in my opinion. The project would behave differently, completely unexpected. If the tags are changed retroactively, I think it would be best to download the binaries from the website, again.

**Comment by javahippie** [comment] 2018-11-15 14:06
On the other hand, I can't think of any reason why someone would want to run on an older Ethereum version. Stability is important, but I can't think of any need to rebuild the network on an older network. The latest tag is fine for me, go for it.

**Comment by kyriediculous** [comment] 2018-11-16 16:11
Afaik the ppa repo is not official , that's the main difference. 
I submitted a PR for develop.

Even though I'm a contributer now I still got a 403 trying to push directly to this repo.

**Comment by chris-aeviator** [comment] 2019-04-23 11:26
I'm experiencing this issue when cloning your repo & running `docker-compose up` in the build step of `bootnode`

**Comment by javahippie** [comment] 2019-04-23 12:59
Hi Chris. Thanks for reporting this, I will try to reproduce the issue, and reopened it.

**Comment by javahippie** [comment] 2019-06-19 20:41
Hey @chris-aeviator, I am not able to reproduce the issue. Do you still have trouble bringing the network up?

**Comment by chris-aeviator** [comment] 2019-06-21 07:54
I was able to bring it up but filed the issue for completenes and awareness. Unfortunately I cannot recall what I did to get it running.

Am 19. Juni 2019 22:41:17 MESZ schrieb "Tim Zöller" <notifications@github.com>:

**Comment by javahippie** [comment] 2019-06-21 08:10
Thanks for the quick reply! 
I removed all locally cached images from my machine, and built the network again, from scratch. I did not run into any issues so I would close it, again, if it is working for you, too.

**Closed by javahippie** 2019-06-21 08:10 UTC
Labels: bug

**Comment by chris-aeviator** [comment] 2019-06-25 09:11
👍
